/**
 * Story Lab's dice: new worlds, heroes, opponents, powers and title shapes,
 * ready to add one at a time.
 *
 * Every entry here is written the way the lore is — each world's institution,
 * roster weakest-first and apex; each hero's version lock, ability ladder and
 * the limits a script has to respect; each power's catch — so an added one
 * makes blueprints as exact as the ones learned from the scripts. None of them
 * is in the lore yet; a roll only ever offers something new. A title shape is
 * a new way to title a format the scripts already built, and uses that
 * format's structure part by part.
 */
import type { FormatId } from "./formats.js";
import type { Hero, Power, World } from "./lore.js";

export type DiceKind = "shape" | "hero" | "world" | "power" | "target";

export interface Shape {
  id: string;
  name: string;
  /** The format whose structure it's built on. */
  base: FormatId;
  /** With {hero}, {world}, {power}, {target}. */
  title: string;
  pitch: string;
}

export const DICE_LABELS: Record<DiceKind, string> = {
  shape: "Format",
  hero: "Hero",
  world: "World or setting",
  power: "Power",
  target: "Target or opponent",
};

export const DICE_SHAPES: Shape[] = [
  {
    id: "hundreddays",
    name: "100 days",
    base: "survive",
    title: "Could {hero} Survive 100 Days In {world}?",
    pitch: "The survival test against a clock: each part is a stretch of days, the setting's pressure rises on a schedule, and the ending is day 100 — or the day before it.",
  },
  {
    id: "raisedin",
    name: "Raised in",
    base: "insert",
    title: "What If {hero} Was Raised In {world}?",
    pitch: "The insertion from childhood: the institution finds the hero young and does the shaping, so the roster and the apex meet someone who grew up inside their system instead of breaking into it.",
  },
  {
    id: "speedrun",
    name: "Speedrun",
    base: "survive",
    title: "How Fast Could {hero} Beat {world}?",
    pitch: "The survival test played for time: every part is the fastest way past the setting's next threat, using only what the hero can actually do.",
  },
  {
    id: "huntedby",
    name: "Hunted by",
    base: "hunt",
    title: "Could {target} Escape {hero}?",
    pitch: "The detective duel from the other side: the target's cover, the mistakes and the moment the net closes, told from the one being hunted.",
  },
  {
    id: "youvillain",
    name: "YOU as the villain",
    base: "you",
    title: "What If YOU Were The Villain In {world}?",
    pitch: "Second person, switched sides: the viewer takes the villain's role and the world's heroes come for them, part by part.",
  },
  {
    id: "laststanding",
    name: "Last one standing",
    base: "survive",
    title: "Could {hero} Be The Last One Standing In {world}?",
    pitch: "The survival test to the end: everyone else in the setting falls part by part, and the question is whether the hero is still there when it's over.",
  },
];

export const DICE_WORLDS: World[] = [
  {
    id: "mha",
    name: "My Hero Academia",
    aliases: ["My Hero Academia", "MHA", "U.A."],
    kind: "universe",
    powered: "Quirk user",
    truth: "80% of people have a Quirk, heroes are licensed and ranked, and the Hero Public Safety Commission decides who counts as one",
    arrival: "the spring before the U.S.J. attack, while All Might's secret is still a secret",
    incident: "a villain attack in the street, and {he} stops it without a hero license — which here is a crime",
    institution: {
      name: "the Hero Public Safety Commission",
      cantClassify: "the Quirk registry has nothing on {him}, and the pinky-toe X-ray that marks the Quirkless says {he} should have a Quirk — yet what {he} does isn't one",
      approach: "U.A. offers {him} a place and a provisional license; the Commission wants {him} registered, ranked and controlled",
    },
    anchors: ["the U.S.J. attack", "the Sports Festival", "the Hero Killer Stain", "the Forest Training Camp", "Kamino and All Might's last fight", "Overhaul", "the Paranormal Liberation War", "the Final War"],
    ladder: [
      { name: "Stain", test: "Bloodcurdle — one taste of {his} blood and {he} can't move" },
      { name: "Dabi", test: "blue flames hotter than his own body can take" },
      { name: "Overhaul", test: "disassembling and rebuilding anything he touches" },
      { name: "Tomura Shigaraki", test: "Decay — one touch, and it spreads" },
      { name: "All For One", test: "a century of stolen Quirks" },
    ],
    apex: {
      name: "All For One",
      firstClash: "doesn't fight {him} at first — he watches, then reaches for whatever power {he} has, to take it",
      leverage: "Shigaraki, and the heroes' secrets he already knows",
      weakness: "a power that isn't a Quirk can't be stolen, and his body is failing",
    },
    endgame: "All For One beaten in the Final War, his stolen Quirks turned against him",
    aftermath: "whether heroes are a ranked job or people who help",
    wants: ["outsider", "hax", "moral", "brute"],
    fresh: true,
  },
  {
    id: "naruto",
    name: "Naruto",
    aliases: ["Naruto", "the Hidden Leaf", "Konoha"],
    kind: "universe",
    powered: "shinobi",
    truth: "every village runs on child soldiers and chakra, and the Nine-Tailed Fox is sealed inside a boy the village hates",
    arrival: "just before the Chunin Exams, with Orochimaru already inside the Leaf",
    incident: "a rogue ninja's jutsu hits {him} and does nothing — no chakra, no hand signs, and {he} still hits back",
    institution: {
      name: "the Hidden Leaf and its Hokage",
      cantClassify: "a Hyuga's Byakugan sees no chakra network in {him} at all",
      approach: "the Third Hokage wants {him} as an ally; Danzo's Root wants {him} studied, or dead",
    },
    anchors: ["the Chunin Exams and Orochimaru's attack", "Sasuke leaving the village", "the Akatsuki hunting jinchuriki", "Pain's attack on the Leaf", "the Fourth Great Ninja War", "Madara and the Infinite Tsukuyomi"],
    ladder: [
      { name: "Zabuza and Haku", test: "the Hidden Mist and ice mirrors" },
      { name: "Orochimaru", test: "snakes, curse marks and a body that won't stay dead" },
      { name: "Itachi", test: "Tsukuyomi — a genjutsu that attacks the mind" },
      { name: "Pain", test: "six bodies and Almighty Push" },
      { name: "Madara", test: "the Rinnegan, Susanoo and a falling meteor" },
    ],
    apex: {
      name: "Madara Uchiha",
      firstClash: "treats {him} as a curiosity and drops a meteor to see what {he} does",
      leverage: "the Infinite Tsukuyomi — everyone {he}'s met, asleep in a dream",
      weakness: "his pride, and Black Zetsu's betrayal",
    },
    endgame: "the Infinite Tsukuyomi broken before Kaguya returns",
    aftermath: "five villages at peace for the first time",
    wants: ["hax", "brute", "outsider", "moral"],
    fresh: true,
  },
  {
    id: "onepiece",
    name: "One Piece",
    aliases: ["One Piece", "the Grand Line", "Straw Hats"],
    kind: "universe",
    powered: "Devil Fruit user",
    truth: "the World Government erased a century of history, and the sea drowns anyone who ate a Devil Fruit",
    arrival: "as the Straw Hats enter the Grand Line",
    incident: "a Marine vice admiral's attack lands and doesn't hurt {him} — no Haki, no Devil Fruit",
    institution: {
      name: "the World Government and the Marines",
      cantClassify: "Sea Prism Stone does nothing to {him} — {he} isn't a Devil Fruit user — and Observation Haki reads nothing unusual",
      approach: "a bounty first; then CP9; then an Admiral",
    },
    anchors: ["Arlong Park", "Alabasta", "Enies Lobby", "Marineford", "Wano", "Egghead"],
    ladder: [
      { name: "Crocodile", test: "a sand body only water or Haki can hit" },
      { name: "Rob Lucci", test: "the Six Powers — Tekkai, Soru, Shigan" },
      { name: "Admiral Kizaru", test: "light — kicks at the speed of light" },
      { name: "Kaido", test: "the strongest creature alive — a dragon form and Conqueror's Haki" },
      { name: "Blackbeard", test: "two Devil Fruits, and darkness that cancels powers" },
    ],
    apex: {
      name: "Fleet Admiral Akainu",
      firstClash: "magma first, questions never — Absolute Justice has no room for something it can't explain",
      leverage: "a Buster Call on whichever island sheltered {him}",
      weakness: "his own rigidity — at Marineford even his Marines started refusing his orders",
    },
    endgame: "the Void Century made public, the way Vegapunk's broadcast began to",
    aftermath: "a sea with no one in charge of it",
    wants: ["brute", "outsider", "moral", "hax"],
    fresh: true,
  },
  {
    id: "bleach",
    name: "Bleach",
    aliases: ["Bleach", "Soul Society", "Gotei 13"],
    kind: "universe",
    powered: "Soul Reaper",
    truth: "Soul Reapers ferry the dead, Hollows eat souls, and the Soul Society's order is built on sins it sealed away",
    arrival: "the week Rukia gives Ichigo her powers",
    incident: "a Hollow's jaws close on {him} and break — and {he} can see it, though {he} isn't a spirit",
    institution: {
      name: "the Soul Society and the Gotei 13",
      cantClassify: "no Zanpakuto and no spiritual pressure they can read — Mayuri can't classify {him}",
      approach: "Captain-Commander Yamamoto orders {him} brought in; Mayuri wants {him} on a table",
    },
    anchors: ["Rukia's execution", "Aizen's betrayal", "Hueco Mundo and the Espada", "the Fake Karakura Town battle", "the Thousand-Year Blood War"],
    ladder: [
      { name: "Byakuya Kuchiki", test: "Senbonzakura — a thousand blades like petals" },
      { name: "Kenpachi Zaraki", test: "a man who only wants the fight to last longer" },
      { name: "Ulquiorra", test: "a second release nobody else has" },
      { name: "Aizen", test: "Kyoka Suigetsu — total hypnosis for anyone who saw it released" },
      { name: "Yhwach", test: "The Almighty — he sees the future and rewrites it" },
    ],
    apex: {
      name: "Aizen",
      firstClash: "is already a step ahead — the first time, {he} was fighting an illusion",
      leverage: "Kyoka Suigetsu on everyone around {him}",
      weakness: "his arrogance, and anyone who never saw Kyoka Suigetsu released",
    },
    endgame: "Aizen sealed, or Yhwach stopped before he merges the worlds",
    aftermath: "the truth about the Soul King",
    wants: ["hax", "brute", "outsider", "moral"],
    fresh: true,
  },
  {
    id: "dragonball",
    name: "Dragon Ball",
    aliases: ["Dragon Ball", "Dragon Ball Z", "DBZ", "Dragon Ball Super"],
    kind: "universe",
    powered: "fighter",
    truth: "power has no ceiling, the Dragon Balls undo death, and gods of destruction watch the whole universe",
    arrival: "the day the Saiyans land on Earth",
    incident: "a scouter reads {his} power level as nothing — then {he} stops a Saibaman bare-handed",
    institution: {
      name: "the Z Fighters and Capsule Corp",
      cantClassify: "scouters can't read {him}, and Piccolo can't sense {his} ki",
      approach: "Bulma wants to study {him}; Vegeta wants to fight {him}",
    },
    anchors: ["the Saiyans' arrival", "Namek and Frieza", "the Androids", "the Cell Games", "Majin Buu", "Beerus", "the Tournament of Power"],
    ladder: [
      { name: "Vegeta", test: "the Galick Gun, and a Saiyan's pride" },
      { name: "Frieza", test: "transformations, Death Beams, and he survives in space" },
      { name: "Cell", test: "regenerating from a single cell" },
      { name: "Majin Buu", test: "absorbing fighters, and re-forming from pieces" },
      { name: "Beerus", test: "Hakai — destruction at a touch" },
    ],
    apex: {
      name: "Beerus",
      firstClash: "only tests {him} — with one finger",
      leverage: "threatens to destroy the Earth over a meal",
      weakness: "boredom and food, and Whis holding him back",
    },
    endgame: "surviving the Tournament of Power",
    aftermath: "a place among the gods — or erased with {his} universe",
    wants: ["brute", "cosmic", "outsider"],
    fresh: true,
  },
  {
    id: "sololeveling",
    name: "Solo Leveling",
    aliases: ["Solo Leveling", "Hunters Association"],
    kind: "universe",
    powered: "Hunter",
    truth: "Gates open onto monster dungeons, Hunters are ranked E to S when they awaken, and nobody's rank ever changes",
    arrival: "the week of the Double Dungeon",
    incident: "a Gate breaks open in the city and {he} walks in, though {he} never awakened",
    institution: {
      name: "the Korean Hunters Association",
      cantClassify: "the mana measuring device reads nothing — no mana, no rank",
      approach: "Chairman Go Gun-Hee wants {him} measured and ranked; the big guilds want {him} signed",
    },
    anchors: ["the Double Dungeon", "the Red Gate", "Jeju Island and the Ant King", "the Monarchs' war", "the Rulers"],
    ladder: [
      { name: "Kang Taeshik", test: "an assassin in a dungeon where no one would find the body" },
      { name: "Baruka", test: "the Ice Elves' chief, fast, inside a Red Gate with no way out" },
      { name: "the Ant King", test: "evolving by eating Hunters" },
      { name: "the Monarch of Frost", test: "a Monarch — a king with an army" },
      { name: "Antares", test: "the Monarch of Destruction and his dragons" },
    ],
    apex: {
      name: "Antares",
      firstClash: "sends his dragons first and watches how {he} handles them",
      leverage: "the cities his dragons can reach",
      weakness: "the Shadow Monarch's army — and the Rulers' war with him",
    },
    endgame: "the Monarchs' war ended",
    aftermath: "whether the Gates stop opening",
    wants: ["hax", "brute", "outsider"],
    fresh: true,
  },
  {
    id: "opm",
    name: "One Punch Man",
    aliases: ["One Punch Man", "Hero Association"],
    kind: "universe",
    powered: "hero",
    truth: "the Hero Association ranks heroes by class and points, and rates disasters from Wolf to God",
    arrival: "the week the Sea Folk attack",
    incident: "{he} ends a Demon-level threat before any ranked hero arrives — and nobody believes it",
    institution: {
      name: "the Hero Association",
      cantClassify: "{his} results don't fit their ranking — top marks on the fitness test and no record of anything {he}'s done",
      approach: "they sign {him} at C-Class, then scramble to promote {him}",
    },
    anchors: ["the Deep Sea King", "Boros's ship", "the Monster Association", "Garou", "the raid on the Monster Association's lair"],
    ladder: [
      { name: "Speed-o'-Sound Sonic", test: "speed, and a grudge" },
      { name: "the Deep Sea King", test: "a monster at full strength in the rain" },
      { name: "Garou", test: "a hero hunter who adapts in the middle of a fight" },
      { name: "Orochi", test: "the Monster King" },
      { name: "Boros", test: "the Collapsing Star Roaring Cannon" },
    ],
    apex: {
      name: "Saitama",
      firstClash: "doesn't take it seriously — he just wants a fight that lasts",
      leverage: "none — he's the one person who can't be leveraged",
      weakness: "boredom",
    },
    endgame: "the Monster Association destroyed",
    aftermath: "a ranking that finally has to explain the one hero at the bottom",
    wants: ["brute", "hax", "outsider"],
    fresh: true,
  },
  {
    id: "hp",
    name: "Harry Potter",
    aliases: ["Harry Potter", "Hogwarts", "Wizarding World"],
    kind: "universe",
    powered: "wizard",
    truth: "wizards hide from Muggles, the Ministry of Magic keeps the secret, and Voldemort is coming back",
    arrival: "Harry's fourth year, the year of the Triwizard Tournament",
    incident: "a Death Eater's Stunner hits {him} and does nothing — and {he} isn't holding a wand",
    institution: {
      name: "the Ministry of Magic",
      cantClassify: "the Trace can't pick up what {he} does — because it isn't magic",
      approach: "Dumbledore wants {him} close; Fudge wants {him} contained; the Unspeakables want to study {him}",
    },
    anchors: ["the Triwizard Tournament", "the graveyard and Voldemort's return", "the Department of Mysteries", "Dumbledore's death", "the Battle of Hogwarts"],
    ladder: [
      { name: "Dementors", test: "they feed on happiness — does {he} even have what they eat?" },
      { name: "Death Eaters", test: "numbers, and curses from the dark" },
      { name: "Bellatrix Lestrange", test: "the Cruciatus Curse" },
      { name: "Voldemort", test: "Avada Kedavra — there's no counter-curse" },
    ],
    apex: {
      name: "Voldemort",
      firstClash: "Avada Kedavra, the curse that has never failed but once",
      leverage: "the students at Hogwarts",
      weakness: "his Horcruxes, and the Elder Wand's loyalty",
    },
    endgame: "the Horcruxes destroyed and the Battle of Hogwarts won",
    aftermath: "a Ministry that has to admit it lied",
    wants: ["hax", "moral", "outsider", "tech"],
    fresh: true,
  },
  {
    id: "got",
    name: "Game of Thrones",
    aliases: ["Game of Thrones", "Westeros", "the Iron Throne"],
    kind: "universe",
    truth: "the Seven Kingdoms fight over the Iron Throne while the dead march south from beyond the Wall",
    arrival: "the year Ned Stark rides south to be Hand of the King",
    incident: "a Kingsguard knight's sword breaks on {him} in the streets of King's Landing",
    institution: {
      name: "the Iron Throne and the Small Council",
      cantClassify: "the maesters have no record of anything like {him} — and the Red Priests say their god foretold {him}",
      approach: "Littlefinger wants to use {him}; Cersei wants {him} dead; Varys wants to know who {he} serves",
    },
    anchors: ["Ned Stark's execution", "the Battle of the Blackwater", "the Red Wedding", "Hardhome", "the Battle of the Bastards", "the Long Night"],
    ladder: [
      { name: "the Mountain", test: "size and cruelty" },
      { name: "the Kingsguard", test: "the best swords in the realm" },
      { name: "Drogon", test: "dragonfire" },
      { name: "the White Walkers", test: "only dragonglass or Valyrian steel kills them" },
      { name: "the Night King", test: "every body that falls gets back up for him" },
    ],
    apex: {
      name: "the Night King",
      firstClash: "never speaks — he raises the dead the hero just killed",
      leverage: "every death on the living's side joins his army",
      weakness: "dragonglass and Valyrian steel",
    },
    endgame: "the Long Night ended at Winterfell",
    aftermath: "who ends up on the Iron Throne",
    wants: ["brute", "moral", "street", "hax"],
    fresh: true,
  },
  {
    id: "strangerthings",
    name: "Stranger Things",
    aliases: ["Stranger Things", "Hawkins", "the Upside Down"],
    kind: "universe",
    powered: "psychic",
    truth: "Hawkins Lab opened a gate to the Upside Down, and something on the other side is coming through",
    arrival: "November 1983, the week Will Byers goes missing",
    incident: "the Demogorgon comes through a wall, and {he} hurts it",
    institution: {
      name: "Hawkins National Laboratory",
      cantClassify: "Dr. Brenner's tests find no psychic ability — {he} just shouldn't be able to do what {he} does",
      approach: "Brenner wants {him} in the lab; the government wants it buried",
    },
    anchors: ["Will's disappearance", "the Mind Flayer in Will", "Starcourt Mall and the Russians", "Vecna's curse", "the Upside Down breaking into Hawkins"],
    ladder: [
      { name: "the Demogorgon", test: "it comes through walls, and heals" },
      { name: "the Demodogs", test: "a pack" },
      { name: "the Mind Flayer", test: "it possesses people and builds a body out of them" },
      { name: "Vecna", test: "his curse kills you from inside your own memories" },
    ],
    apex: {
      name: "Vecna",
      firstClash: "doesn't meet {him} — he goes for {his} mind first",
      leverage: "{his} friends' worst memories",
      weakness: "a song that pulls a victim back, and his body lying in the Upside Down",
    },
    endgame: "Vecna killed in the Upside Down",
    aftermath: "Hawkins, and whether the gates ever close",
    wants: ["hax", "moral", "outsider", "tech"],
    fresh: true,
  },
  {
    id: "hungergames",
    name: "The Hunger Games",
    aliases: ["The Hunger Games", "Hunger Games", "the Capitol"],
    kind: "setting",
    goal: "be the last tribute alive — or break the Games",
    truth: "twenty-four tributes, one survivor, and the whole Capitol watching",
    arrival: "the reaping in District 12",
    incident: "the gong sounds and the bloodbath at the Cornucopia starts",
    institution: {
      name: "the Capitol and the Gamemakers",
      cantClassify: "a tribute whose body the arena wasn't designed for",
      approach: "the Gamemakers change the arena around {him}; President Snow wants {him} to lose on camera",
    },
    anchors: ["the reaping", "the Cornucopia bloodbath", "the tracker jackers", "the feast", "the final three"],
    ladder: [
      { name: "the Careers", test: "a trained pack" },
      { name: "the Gamemakers' mutts", test: "creatures built for the arena" },
      { name: "the fire wall", test: "the arena itself" },
      { name: "the last tribute", test: "someone else who has to win too" },
    ],
    apex: {
      name: "President Snow",
      firstClash: "sends a message through the Gamemakers — the arena turns on {him}",
      leverage: "{his} district, and whoever {he}'s grown close to",
      weakness: "a victor the districts love",
    },
    rules: "the arena kills you if the other tributes don't — fire, water, mutts",
    attrition: "food, water and sponsors",
    dilemma: "winning, or refusing to play Snow's game",
    endgame: "the arena broken, the way the Quarter Quell's was",
    aftermath: "the rebellion {he} started",
    wants: ["street", "moral", "brute", "detective"],
    fresh: true,
  },
  {
    id: "twd",
    name: "The Walking Dead",
    aliases: ["The Walking Dead", "Walking Dead"],
    kind: "setting",
    goal: "survive and keep people alive — the dead are the easy part",
    truth: "everyone is infected: you turn when you die, bitten or not",
    arrival: "the week Rick wakes up in the hospital",
    incident: "{his} first walkers, and the only rule that matters: the brain, only the brain",
    institution: {
      name: "the communities — Woodbury, Terminus, the Saviors",
      cantClassify: "someone who could clear the walkers on {his} own",
      approach: "the Governor offers a home; Negan offers a choice",
    },
    anchors: ["the CDC", "the prison and Woodbury", "Terminus", "Alexandria", "Negan and the Saviors", "the Whisperers"],
    ladder: [
      { name: "a herd", test: "thousands of walkers moving as one" },
      { name: "the Governor", test: "a tank at the prison" },
      { name: "Terminus", test: "a community that eats people" },
      { name: "Negan", test: "Lucille and a hundred Saviors" },
      { name: "Alpha and the Whisperers", test: "people who walk among the dead" },
    ],
    apex: {
      name: "Negan",
      firstClash: "a lineup in the dark, and Lucille",
      leverage: "the people he'll kill if the hero doesn't kneel",
      weakness: "his own rules, and Saviors tired of kneeling",
    },
    rules: "anyone who dies turns; only a head shot stops them",
    attrition: "ammunition, food and trust",
    dilemma: "save strangers, or protect your own",
    endgame: "the Saviors beaten and the communities rebuilt",
    aftermath: "what civilisation looks like after",
    wants: ["street", "brute", "moral", "regen"],
    fresh: true,
  },
  {
    id: "jurassicpark",
    name: "Jurassic Park",
    aliases: ["Jurassic Park", "Jurassic World", "Isla Nublar"],
    kind: "setting",
    goal: "get off Isla Nublar alive",
    truth: "the dinosaurs are real, the park isn't ready, and the power just went out",
    arrival: "the weekend of the tour, the night the storm hits",
    incident: "the fences go down and the T. rex walks out",
    institution: {
      name: "InGen",
      cantClassify: "a visitor the park's security has no protocol for",
      approach: "Hammond wants his park saved; InGen's men want what the embryos are worth",
    },
    anchors: ["the T. rex paddock", "the raptor pen", "restarting the power", "the visitor centre kitchen", "the helicopter off the island"],
    ladder: [
      { name: "the Dilophosaurus", test: "venom in the dark" },
      { name: "the T. rex", test: "size, and a road it owns" },
      { name: "the Velociraptors", test: "pack hunters that test the fences" },
      { name: "the Indominus rex", test: "a hybrid built to hunt and to hide" },
    ],
    apex: {
      name: "the Velociraptors",
      firstClash: "they test the fences for weak spots — systematically, never in the same place twice",
      leverage: "the kids",
      weakness: "they fight each other, and the T. rex",
    },
    rules: "no power means no fences",
    attrition: "daylight, ammunition, and how long the generator runs",
    dilemma: "save the park's people, or let the island go",
    endgame: "the helicopter off Isla Nublar",
    aftermath: "InGen's embryos, and Site B",
    wants: ["brute", "tech", "street", "detective"],
    fresh: true,
  },
  {
    id: "alien",
    name: "Alien",
    aliases: ["Alien", "Xenomorph", "Nostromo"],
    kind: "setting",
    goal: "keep the Xenomorph from killing the crew — and from reaching Earth",
    truth: "the company wants the creature alive, and the crew is expendable",
    arrival: "aboard the Nostromo, the day Kane is carried back with something on his face",
    incident: "the chestburster, at dinner",
    institution: {
      name: "Weyland-Yutani",
      cantClassify: "a crew member Ash's orders never accounted for",
      approach: "Ash's standing order: bring the organism back, crew expendable",
    },
    anchors: ["the derelict ship", "the chestburster", "the air ducts", "Ash's betrayal", "the self-destruct", "the escape shuttle"],
    ladder: [
      { name: "the facehugger", test: "acid for blood, and it can't be pulled off" },
      { name: "the Xenomorph", test: "a hunter in the vents" },
      { name: "Ash", test: "a synthetic under company orders" },
      { name: "the Queen", test: "a hive" },
    ],
    apex: {
      name: "the Xenomorph",
      firstClash: "it drops from the ceiling",
      leverage: "the crew, one at a time",
      weakness: "fire, and the airlock",
    },
    rules: "acid blood — shoot it and it eats through the hull",
    attrition: "air, crew, and minutes before the self-destruct",
    dilemma: "obey the company, or blow the ship",
    endgame: "the creature blown out of the airlock",
    aftermath: "the company's next mission",
    wants: ["tech", "brute", "street", "regen"],
    fresh: true,
  },
];

export const DICE_HEROES: Hero[] = [
  {
    id: "naruto",
    name: "Naruto",
    aliases: ["Naruto", "Naruto Uzumaki"],
    from: "Naruto",
    home: "naruto",
    version: "Naruto in the Fourth Great Ninja War with Kurama cooperating — Sage Mode and Kurama Chakra Mode, before the Six Paths power",
    ladder: ["Shadow Clone Jutsu", "Rasengan", "Sage Mode", "Rasenshuriken", "Kurama Chakra Mode", "Tailed Beast Bomb"],
    limits: [
      "Sage Mode runs out unless a clone is gathering nature energy somewhere still",
      "Shadow Clones split his chakra, and every clone's fatigue comes back to him",
      "he's no good at genjutsu",
    ],
    code: "never gives up and never abandons a friend — he talks to an enemy before he kills one",
    engine: "the boy everyone ignored, who turns every enemy into someone he understands",
    tags: ["brute", "moral", "outsider"],
    fresh: true,
  },
  {
    id: "luffy",
    name: "Luffy",
    aliases: ["Luffy", "Monkey D. Luffy"],
    from: "One Piece",
    home: "onepiece",
    version: "Luffy after Wano, with Gear 5 awakened",
    ladder: ["Gum-Gum Pistol", "Gear 2", "Armament Haki", "Gear 4 (Boundman)", "Advanced Conqueror's Haki", "Gear 5"],
    limits: [
      "a Devil Fruit user — the sea and Sea Prism Stone drain him",
      "Gear 4 and Gear 5 leave him spent",
      "he doesn't plan — his crew does",
    ],
    code: "freedom — he fights anyone who takes it from someone, and he doesn't kill",
    engine: "a rubber man whose fights turn ridiculous right when they should be hopeless",
    tags: ["brute", "moral", "outsider"],
    fresh: true,
  },
  {
    id: "ichigo",
    name: "Ichigo",
    aliases: ["Ichigo", "Ichigo Kurosaki"],
    from: "Bleach",
    home: "bleach",
    version: "Ichigo in the Thousand-Year Blood War, with his true Zangetsu",
    ladder: ["Getsuga Tensho", "Bankai — Tensa Zangetsu", "the Hollow mask", "his Quincy blood", "Fullbring", "his true Bankai"],
    limits: [
      "pushed far enough, his Hollow side takes over",
      "he never learned kido",
      "the Final Getsuga Tensho cost him his powers once",
    ],
    code: "protect the people he can reach",
    engine: "part Soul Reaper, part Hollow, part Quincy — the one person every side claims",
    tags: ["brute", "moral", "regen"],
    fresh: true,
  },
  {
    id: "deku",
    name: "Deku",
    aliases: ["Deku", "Izuku Midoriya"],
    from: "My Hero Academia",
    home: "mha",
    version: "Deku in the Final War — One For All near full power, with the vestiges' Quirks",
    ladder: ["Full Cowl", "Shoot Style", "Blackwhip", "Float", "Danger Sense", "One For All at 100%"],
    limits: [
      "100% breaks his bones without Full Cowl's control",
      "every vestige's Quirk costs him stamina",
      "he overthinks — he plans in the middle of the fight",
    ],
    code: "save everyone — even the villains",
    engine: "a Quirkless kid who inherited the Symbol of Peace's power and has to learn it by breaking himself",
    tags: ["brute", "moral", "detective"],
    fresh: true,
  },
  {
    id: "tanjiro",
    name: "Tanjiro",
    aliases: ["Tanjiro", "Tanjiro Kamado"],
    from: "Demon Slayer",
    home: "demonslayer",
    version: "Tanjiro after the Swordsmith Village, with Sun Breathing and the Mark",
    ladder: ["Water Breathing", "Hinokami Kagura (Sun Breathing)", "his sense of smell", "the Demon Slayer Mark", "the see-through world"],
    limits: ["a human body — no regeneration", "the Mark shortens his life", "he can't make himself hate a demon"],
    code: "kind even to the demons he kills — they were human once",
    engine: "a boy who can smell the lie behind every attack, and still mourns his enemies",
    tags: ["moral", "detective", "street"],
    fresh: true,
  },
  {
    id: "levi",
    name: "Levi",
    aliases: ["Levi", "Levi Ackerman", "Captain Levi"],
    from: "Attack on Titan",
    home: "aot",
    version: "Levi before Shiganshina, at his peak with ODM gear",
    ladder: ["ODM gear", "blades", "thunder spears", "Ackerman strength", "the spin that took down the Beast Titan"],
    limits: ["gas and blades run out", "no powers — one mistake and he's dead", "he can't fly without something to anchor to"],
    code: "choose so you won't regret it — and keep the promise to Erwin",
    engine: "humanity's strongest soldier, with no power at all",
    tags: ["street", "brute"],
    fresh: true,
  },
  {
    id: "kratos",
    name: "Kratos",
    aliases: ["Kratos", "God of War"],
    from: "God of War",
    version: "Kratos in the Norse era (Ragnarök) — the Leviathan Axe, the Blades of Chaos and Spartan Rage",
    ladder: ["the Leviathan Axe", "the Blades of Chaos", "the Guardian Shield", "the Draupnir Spear", "Spartan Rage"],
    limits: ["he holds back to protect Atreus", "Spartan Rage costs him control", "a god can still be outnumbered and outthought"],
    code: "not to be the monster he was — but he'll kill a god who comes for his son",
    engine: "a man who killed the Greek gods, trying to be a father",
    tags: ["brute", "moral", "cosmic"],
    fresh: true,
  },
  {
    id: "masterchief",
    name: "Master Chief",
    aliases: ["Master Chief", "John-117"],
    from: "Halo",
    version: "Master Chief in Halo 3 — MJOLNIR Mark VI armour, with Cortana",
    ladder: ["MJOLNIR armour and its energy shield", "the assault rifle", "Cortana", "the Spartan Laser", "the Energy Sword"],
    limits: ["the shield recharges; the body under it doesn't", "no powers — augmentation and gear", "Cortana has limits of her own"],
    code: "finish the fight",
    engine: "a super-soldier nobody's seen without his helmet, in a world that's never seen what he can do",
    tags: ["tech", "brute", "street"],
    fresh: true,
  },
  {
    id: "johnwick",
    name: "John Wick",
    aliases: ["John Wick", "Baba Yaga"],
    from: "John Wick",
    version: "John Wick in Chapter 4",
    ladder: ["a pistol at arm's length", "a pencil", "the bulletproof suit", "a car", "the High Table's rules"],
    limits: ["just a man — he tires and he bleeds", "the High Table's rules bind him as much as they protect him", "excommunicado — no Continental"],
    code: "you took something from him; he takes it back",
    engine: "the man the killers were afraid of, somewhere fear doesn't work on everyone",
    tags: ["street", "brute"],
    fresh: true,
  },
  {
    id: "strange",
    name: "Doctor Strange",
    aliases: ["Doctor Strange", "Stephen Strange"],
    from: "the MCU",
    home: "mcu",
    version: "Strange after No Way Home — Wong is Sorcerer Supreme, and Strange still breaks the rules",
    ladder: ["sling rings and portals", "the Cloak of Levitation", "the Mirror Dimension", "astral projection", "the Eye of Agamotto — empty since the Time Stone went back"],
    limits: ["no Time Stone after Endgame", "his spells need his hands", "he trusts himself more than anyone"],
    code: "protect reality — he'll make the one-in-fourteen-million choice",
    engine: "a surgeon who sees every angle and still can't fix everything",
    tags: ["hax", "tech", "cosmic"],
    fresh: true,
  },
  {
    id: "wanda",
    pronoun: "she",
    name: "Scarlet Witch",
    aliases: ["Scarlet Witch", "Wanda Maximoff", "Wanda"],
    from: "the MCU",
    home: "mcu",
    version: "Wanda after WandaVision, with the Darkhold",
    ladder: ["telekinesis", "mind control", "chaos magic", "rewriting reality (Westview)", "dreamwalking"],
    limits: ["grief is her power's fuel and its weakness", "the Darkhold corrupts her", "she can be distracted"],
    code: "protect her children, whatever it costs",
    engine: "a woman who can rewrite reality and only wants her family back",
    tags: ["hax", "moral"],
    fresh: true,
  },
  {
    id: "cap",
    name: "Captain America",
    aliases: ["Captain America", "Steve Rogers"],
    from: "the MCU",
    home: "mcu",
    version: "Steve Rogers in Endgame — the shield, and worthy of Mjolnir",
    ladder: ["the vibranium shield", "super-soldier strength", "tactics", "Mjolnir"],
    limits: ["peak human, not superhuman", "he won't leave a teammate", "honest to a fault"],
    code: "he does what's right when nobody else will",
    engine: "a man out of time, with the one thing the world forgot how to be",
    tags: ["moral", "brute", "street"],
    fresh: true,
  },
  {
    id: "tchalla",
    name: "Black Panther",
    aliases: ["Black Panther", "T'Challa"],
    from: "the MCU",
    home: "mcu",
    version: "T'Challa in Infinity War — the nanotech suit that stores kinetic energy",
    ladder: ["the vibranium suit", "stored kinetic energy, released", "the Heart-Shaped Herb", "Wakanda's technology", "Shuri"],
    limits: ["the suit's charge runs out", "a king with a country to answer to", "he isn't a god"],
    code: "a king's duty — his people first, then the world",
    engine: "a king with the most advanced technology on Earth, deciding whether to share it",
    tags: ["tech", "moral", "street"],
    fresh: true,
  },
  {
    id: "flash",
    name: "The Flash",
    aliases: ["The Flash", "Barry Allen"],
    from: "DC",
    version: "Barry Allen at his comics peak — the Speed Force, phasing and time travel",
    ladder: ["super speed", "phasing", "the Infinite Mass Punch", "time travel", "the Speed Force"],
    limits: ["changing the past breaks things (Flashpoint)", "his metabolism — he has to eat constantly", "fast isn't everywhere at once"],
    code: "save everyone — and never fix the past, even though he could",
    engine: "the fastest man alive, who can do anything except slow down",
    tags: ["hax", "moral"],
    fresh: true,
  },
  {
    id: "wonderwoman",
    pronoun: "she",
    name: "Wonder Woman",
    aliases: ["Wonder Woman", "Diana Prince"],
    from: "DC",
    version: "Diana in the DCEU — the Lasso of Truth, her bracers and the God Killer",
    ladder: ["her bracers", "the Lasso of Hestia", "the God Killer sword", "flight", "a demigod's strength"],
    limits: ["the Lasso compels the truth — from her too", "a demigod, not invulnerable", "she believes in people, sometimes too much"],
    code: "love and truth — she fights for peace",
    engine: "a goddess who came to save the world and has to decide if it deserves it",
    tags: ["brute", "moral", "cosmic"],
    fresh: true,
  },
  {
    id: "vegeta",
    name: "Vegeta",
    aliases: ["Vegeta"],
    from: "Dragon Ball",
    home: "dragonball",
    version: "Vegeta in Dragon Ball Super, with Ultra Ego",
    ladder: ["the Galick Gun", "Super Saiyan Blue", "Final Flash", "Final Explosion", "Ultra Ego"],
    limits: ["pride — he lets enemies power up", "Ultra Ego lets the damage pile up", "fusion needs Goku"],
    code: "surpass Kakarot — and protect his family",
    engine: "the Saiyan prince who can't stand being second",
    tags: ["brute", "cosmic"],
    fresh: true,
  },
  {
    id: "itachi",
    name: "Itachi",
    aliases: ["Itachi", "Itachi Uchiha"],
    from: "Naruto",
    home: "naruto",
    version: "Itachi at his prime, before his illness took hold",
    ladder: ["the Sharingan", "Tsukuyomi", "Amaterasu", "Susanoo with the Totsuka Blade and the Yata Mirror", "Izanami"],
    limits: ["his eyes are going blind", "his illness", "the Mangekyo drains him fast"],
    code: "the village first, even over his own name",
    engine: "the traitor who was the most loyal ninja of all",
    tags: ["hax", "detective", "moral"],
    fresh: true,
  },
  {
    id: "eleven",
    pronoun: "she",
    name: "Eleven",
    aliases: ["Eleven"],
    from: "Stranger Things",
    home: "strangerthings",
    version: "Eleven in Season 4, after her powers come back",
    ladder: ["telekinesis", "remote viewing through the Void", "reading minds in the Void", "opening a gate"],
    limits: ["nosebleeds — too much hurts her", "she has to concentrate", "she's a kid"],
    code: "friends don't lie",
    engine: "a child weapon who only wants to be normal",
    tags: ["hax", "moral", "outsider"],
    fresh: true,
  },
  {
    id: "leon",
    name: "Leon Kennedy",
    aliases: ["Leon Kennedy", "Leon S. Kennedy"],
    from: "Resident Evil",
    home: "re",
    version: "Leon in Resident Evil 4 — a government agent with years of bioweapons behind him",
    ladder: ["a pistol and a combat knife", "the suplex", "a rifle", "the rocket launcher"],
    limits: ["human", "ammunition runs out", "a mission to finish — and someone to bring home"],
    code: "save the person he was sent for",
    engine: "a rookie cop who survived Raccoon City and never stopped running into its kind",
    tags: ["street", "tech"],
    fresh: true,
  },
  {
    id: "geralt",
    name: "Geralt",
    aliases: ["Geralt", "Geralt of Rivia", "The Witcher"],
    from: "The Witcher",
    version: "Geralt in The Witcher 3",
    ladder: ["the steel sword, for men", "the silver sword, for monsters", "Signs — Igni, Aard, Quen, Axii, Yrden", "potions and oils", "a bestiary's worth of knowledge"],
    limits: ["potions are toxic", "a monster hunter, not a soldier against armies", "he stays out of politics — until he can't"],
    code: "the lesser evil — and he won't kill a creature for coin if it's no threat",
    engine: "a mutant hunter who studies a monster before he fights it",
    tags: ["detective", "brute", "outsider"],
    fresh: true,
  },
  {
    id: "doomslayer",
    name: "Doom Slayer",
    aliases: ["Doom Slayer", "Doomguy"],
    from: "DOOM",
    version: "the Doom Slayer in DOOM Eternal",
    ladder: ["the Super Shotgun and its Meat Hook", "the Chainsaw", "Berserk", "the BFG 9000", "the Crucible"],
    limits: ["he isn't there to talk", "only the Praetor Suit protects him", "he runs on ammunition he has to take from demons"],
    code: "rip and tear, until it is done",
    engine: "the thing Hell is afraid of",
    tags: ["brute", "outsider"],
    fresh: true,
  },
  {
    id: "toji",
    name: "Toji",
    aliases: ["Toji", "Toji Fushiguro"],
    from: "Jujutsu Kaisen",
    home: "jjk",
    version: "Toji in the Star Plasma Vessel arc",
    ladder: ["Heavenly Restriction", "the Inverted Spear of Heaven", "Playful Cloud", "the Split Soul Katana", "the chain"],
    limits: ["no cursed energy — barriers can't see him, and he can't use techniques", "a hired gun — it's about the money", "he only takes fights he can win"],
    code: "the job, and never a fight he can't win",
    engine: "a man with no cursed energy who nearly killed the strongest sorcerer",
    tags: ["street", "brute", "hax"],
    fresh: true,
  },
  {
    id: "yuta",
    name: "Yuta",
    aliases: ["Yuta", "Yuta Okkotsu"],
    from: "Jujutsu Kaisen",
    home: "jjk",
    version: "Yuta after Shibuya, with Rika",
    ladder: ["Rika", "copying techniques", "Reverse Cursed Technique", "the Pure Love beam", "Domain Expansion: Authentic Mutual Love"],
    limits: ["copying needs Rika fully manifested — five minutes at a time", "huge cursed energy, control learned late", "he loves too hard"],
    code: "he'll protect his friends, and do the terrible thing if it has to be done",
    engine: "a boy haunted by the curse of the girl he loved",
    tags: ["hax", "moral"],
    fresh: true,
  },
  {
    id: "sherlock",
    name: "Sherlock Holmes",
    aliases: ["Sherlock Holmes", "Sherlock"],
    from: "Sherlock Holmes",
    version: "Holmes of the original stories — Baker Street, Watson and the Irregulars",
    ladder: ["deduction", "disguise", "boxing and baritsu", "the Baker Street Irregulars", "Watson"],
    limits: ["boredom", "he needs data before he theorises", "Moriarty is his equal"],
    code: "the truth — and justice when the law fails",
    engine: "a man who reads a stranger's life off their sleeve",
    tags: ["detective", "street"],
    role: "detective",
    fresh: true,
  },
];

export const DICE_TARGETS: Hero[] = [
  {
    id: "hannibal",
    name: "Hannibal Lecter",
    aliases: ["Hannibal Lecter", "Hannibal"],
    from: "The Silence of the Lambs",
    version: "Dr. Lecter before his capture — a respected psychiatrist in Baltimore",
    hides: "he's the psychiatrist the investigators ask for help",
    ladder: ["psychiatry — he reads anyone", "a surgeon's knowledge", "his social standing", "patience"],
    limits: ["pride — he leaves signatures for someone clever enough", "courtesy is a rule to him"],
    code: "rudeness is the crime",
    engine: "a killer who's the smartest man in every room",
    tags: ["villain", "detective"],
    role: "target",
    fresh: true,
  },
  {
    id: "moriarty",
    name: "Moriarty",
    aliases: ["Moriarty", "Professor Moriarty"],
    from: "Sherlock Holmes",
    version: "Professor Moriarty — the Napoleon of crime",
    hides: "he never commits a crime himself; he plans them for others",
    ladder: ["a criminal network", "mathematics", "blackmail"],
    limits: ["he needs a worthy opponent", "his web is only as loyal as it's paid"],
    code: "boredom is the enemy",
    engine: "a spider at the centre of a web of a thousand crimes",
    tags: ["villain", "detective"],
    role: "target",
    fresh: true,
  },
  {
    id: "johan",
    name: "Johan Liebert",
    aliases: ["Johan Liebert", "Johan"],
    from: "Monster",
    version: "Johan in Monster",
    hides: "everyone who meets him remembers only kindness — and the few who know are dead",
    ladder: ["manipulation", "followers who'd die for him", "an alibi for everything"],
    limits: ["his twin sister", "he wants to be seen for what he is"],
    code: "to be the last one standing, and see the end",
    engine: "the perfect monster, with no face",
    tags: ["villain", "detective"],
    role: "target",
    fresh: true,
  },
  {
    id: "ghostface",
    name: "Ghostface",
    aliases: ["Ghostface"],
    from: "Scream",
    version: "the original Woodsboro killers",
    hides: "there are two of them, and they're people you already know",
    ladder: ["a knife and a phone", "the mask", "an accomplice"],
    limits: ["they want to be caught on their own terms", "they play by horror-movie rules"],
    code: "the rules of a scary movie",
    engine: "the killer who's always someone in the room",
    tags: ["villain", "street"],
    role: "target",
    fresh: true,
  },
  {
    id: "michaelmyers",
    name: "Michael Myers",
    aliases: ["Michael Myers"],
    from: "Halloween",
    version: "Michael Myers in the original Halloween",
    hides: "he doesn't hide — he just can't be stopped",
    ladder: ["a kitchen knife", "impossible durability", "patience"],
    limits: ["no speech, no motive to read", "his fixation on his sister"],
    code: "none",
    engine: "the Shape — evil that walks",
    tags: ["villain", "brute", "regen"],
    role: "target",
    fresh: true,
  },
  {
    id: "aizen",
    name: "Aizen",
    aliases: ["Aizen", "Sosuke Aizen"],
    from: "Bleach",
    home: "bleach",
    version: "Aizen before the Hogyoku merges with him",
    hides: "everyone who knows the truth is under Kyoka Suigetsu",
    ladder: ["Kyoka Suigetsu — complete hypnosis", "kido without incantation", "the Hogyoku"],
    limits: ["anyone who never saw Kyoka Suigetsu released", "arrogance"],
    code: "to stand in the heavens",
    engine: "the man who planned the whole story",
    tags: ["villain", "hax", "detective"],
    role: "target",
    fresh: true,
  },
  {
    id: "allforone",
    name: "All For One",
    aliases: ["All For One"],
    from: "My Hero Academia",
    home: "mha",
    version: "All For One before Kamino",
    hides: "he's been a myth for a century — even the Commission isn't sure he's real",
    ladder: ["stealing and giving Quirks", "a thousand stolen Quirks", "stacked strength and air cannons", "Shigaraki, his successor"],
    limits: ["his body is failing", "One For All can only be given, never taken"],
    code: "to rule, from the shadows",
    engine: "the Symbol of Evil",
    tags: ["villain", "hax"],
    role: "target",
    fresh: true,
  },
  {
    id: "makima",
    pronoun: "she",
    name: "Makima",
    aliases: ["Makima"],
    from: "Chainsaw Man",
    home: "csm",
    version: "Makima at the height of her control over Public Safety",
    hides: "she is Public Safety — and anyone who suspects her becomes her dog",
    ladder: ["the Control Devil", "a contract with the Prime Minister", "her dogs"],
    limits: ["she sees people only as dogs, or equals", "she can be eaten"],
    code: "a better world, under her control",
    engine: "the boss who owns everyone",
    tags: ["villain", "hax"],
    role: "target",
    fresh: true,
  },
  {
    id: "kingpin",
    name: "Kingpin",
    aliases: ["Kingpin", "Wilson Fisk"],
    from: "Marvel",
    version: "Wilson Fisk in Daredevil",
    hides: "he's the city's philanthropist, and his crimes run through people who'd die before they testify",
    ladder: ["money", "the police", "his strength"],
    limits: ["Vanessa", "his temper"],
    code: "order — his order",
    engine: "the crime lord the whole city is already paying",
    tags: ["villain", "street", "brute"],
    role: "target",
    fresh: true,
  },
  {
    id: "riddler",
    name: "The Riddler",
    aliases: ["The Riddler", "Riddler", "Edward Nashton"],
    from: "DC",
    version: "the Riddler of The Batman (2022)",
    hides: "he's an accountant nobody notices, with followers online",
    ladder: ["riddles and cyphers", "a livestream", "bombs"],
    limits: ["he has to leave clues — he needs to be admired", "he wants Batman to understand him"],
    code: "unmask the city's corruption",
    engine: "the killer who leaves the answers",
    tags: ["villain", "detective"],
    role: "target",
    fresh: true,
  },
];

export const DICE_POWERS: Power[] = [
  {
    id: "sharingan",
    name: "the Sharingan",
    aliases: ["Sharingan", "Mangekyo Sharingan"],
    from: "Naruto",
    grants: ["seeing chakra and predicting movement", "copying any technique it sees", "genjutsu through eye contact", "the Mangekyo — Amaterasu, Tsukuyomi, Susanoo"],
    cantCopy: "the chakra and training to use what it copies — a copied jutsu still needs a body that can do it",
    cost: "the Mangekyo blinds you the more you use it",
    mentor: "Kakashi, who wasn't born with his",
    weakness: "eye contact works both ways — close your eyes and half of it's gone",
  },
  {
    id: "ofa",
    name: "One For All",
    aliases: ["One For All"],
    from: "My Hero Academia",
    grants: ["stockpiled strength that grows with every holder", "Full Cowl speed", "Blackwhip, Float, Danger Sense, Smokescreen, Fa Jin", "the vestiges' advice"],
    cantCopy: "a body trained enough to hold it",
    cost: "at 100% it breaks your bones until your body catches up",
    mentor: "All Might",
    weakness: "All For One hunts every holder",
  },
  {
    id: "nika",
    name: "the Gum-Gum Fruit",
    aliases: ["Gum-Gum Fruit", "Gomu Gomu", "Nika", "Gear 5"],
    from: "One Piece",
    grants: ["a rubber body — blunt hits and lightning do nothing", "Gears 2 to 4", "Gear 5 — the body and the world around it stretch as he imagines"],
    cantCopy: "Haki — that has to be trained",
    cost: "the sea takes it: a Devil Fruit user can never swim again",
    mentor: "Rayleigh, for the Haki",
    weakness: "Sea Prism Stone, and water",
  },
  {
    id: "supersaiyan",
    name: "Super Saiyan",
    aliases: ["Super Saiyan", "Saiyan"],
    from: "Dragon Ball",
    grants: ["a fifty-fold power multiplier", "Super Saiyan 2, 3, God and Blue", "coming back stronger after nearly dying"],
    cantCopy: "ki control — flying and blasts still need training",
    cost: "it's unlocked by rage, and it pushes him to fight",
    mentor: "Vegeta, grudgingly",
    weakness: "stamina — the forms drain fast",
  },
  {
    id: "speedforce",
    name: "the Speed Force",
    aliases: ["Speed Force"],
    from: "DC",
    grants: ["super speed", "phasing through matter", "accelerated healing", "time travel"],
    cantCopy: "a hero's judgement about when not to use it",
    cost: "every trip into the past breaks the timeline",
    mentor: "Barry Allen",
    weakness: "the Reverse-Flash, and a metabolism that needs feeding constantly",
  },
  {
    id: "kurama",
    name: "the Nine-Tails' chakra",
    aliases: ["Nine-Tails", "Kurama", "Nine-Tailed Fox"],
    from: "Naruto",
    grants: ["a near-bottomless chakra supply", "healing", "Tailed Beast Mode", "the Tailed Beast Bomb"],
    cantCopy: "jutsu — chakra isn't technique",
    cost: "Kurama's hatred bleeds into you until you earn his trust",
    mentor: "Killer Bee",
    weakness: "sealing jutsu, and the Akatsuki hunting jinchuriki",
  },
  {
    id: "foundingtitan",
    name: "the Founding Titan",
    aliases: ["Founding Titan", "Titan Shifter", "Titan powers"],
    from: "Attack on Titan",
    grants: ["turning into a Titan", "regeneration", "command over Titans and the Subjects of Ymir", "the Coordinate"],
    cantCopy: "royal blood — the full power needs it",
    cost: "the Curse of Ymir: thirteen years to live",
    mentor: "the memories of the Titan's past holders",
    weakness: "the nape",
  },
  {
    id: "bankai",
    name: "a Zanpakuto with Bankai",
    aliases: ["Bankai", "Zanpakuto"],
    from: "Bleach",
    grants: ["a sword with a spirit and a name", "Shikai — its released form", "Bankai — five to ten times the power", "flash step"],
    cantCopy: "the sword's spirit — it has to be understood, not just held",
    cost: "Bankai takes ten years to master, and it can be stolen",
    mentor: "Urahara",
    weakness: "a Quincy medallion can steal a Bankai",
  },
  {
    id: "kryptonian",
    name: "Kryptonian biology",
    aliases: ["Kryptonian", "Superman's powers"],
    from: "DC",
    grants: ["strength and invulnerability", "flight", "heat vision and freeze breath", "X-ray vision and super hearing"],
    cantCopy: "Clark's restraint — a Smallville upbringing",
    cost: "the world expects him to save everyone",
    mentor: "Superman",
    weakness: "kryptonite, red sunlight and magic",
  },
  {
    id: "healingfactor",
    name: "a healing factor",
    aliases: ["Healing Factor"],
    from: "X-Men",
    grants: ["regenerating from almost any wound", "slowed ageing", "immunity to poison and disease"],
    cantCopy: "adamantium claws — that was Weapon X, not the mutation",
    cost: "you live long enough to lose everyone",
    mentor: "Wolverine",
    weakness: "decapitation, and the Muramasa blade",
  },
  {
    id: "timestone",
    name: "the Time Stone",
    aliases: ["Time Stone", "Eye of Agamotto"],
    from: "the MCU",
    grants: ["reversing time on anything", "time loops", "seeing possible futures"],
    cantCopy: "the mystic arts to use it — it needs a sorcerer",
    cost: "breaking the natural law has consequences",
    mentor: "Doctor Strange",
    weakness: "Thanos is coming for it",
  },
  {
    id: "sunbreathing",
    name: "Sun Breathing",
    aliases: ["Sun Breathing", "Breath of the Sun", "Hinokami Kagura"],
    from: "Demon Slayer",
    grants: ["thirteen forms that burn demons like sunlight", "the Demon Slayer Mark", "the see-through world"],
    cantCopy: "Yoriichi's body — nobody else was born for it",
    cost: "the Mark kills its bearer by twenty-five",
    mentor: "Tanjiro",
    weakness: "a human body — a demon heals, you don't",
  },
  {
    id: "theworld",
    name: "The World",
    aliases: ["The World", "Za Warudo"],
    from: "JoJo's Bizarre Adventure",
    grants: ["a Stand only other Stand users can see", "stopping time for a few seconds", "strength and speed beyond any human"],
    cantCopy: "range — the Stand stays close to him",
    cost: "Stand users are drawn to each other: every one he meets is coming for him",
    mentor: "DIO",
    weakness: "a Stand of the same kind — Star Platinum",
  },
];

/** Every item on the dice, by group. */
export function diceGroups(): Record<DiceKind, Array<{ id: string; name: string; from: string }>> {
  return {
    shape: DICE_SHAPES.map((s) => ({ id: s.id, name: s.name, from: s.title })),
    hero: DICE_HEROES.map((h) => ({ id: h.id, name: h.name, from: h.from })),
    world: DICE_WORLDS.map((w) => ({ id: w.id, name: w.name, from: w.kind === "setting" ? "a survival setting" : "a universe" })),
    power: DICE_POWERS.map((p) => ({ id: p.id, name: p.name, from: p.from })),
    target: DICE_TARGETS.map((h) => ({ id: h.id, name: h.name, from: h.from })),
  };
}
